<?php 
$tableParams = array(
	'tableId' 			=> 'mage-logs-tree',
    'tableWidth'        => '4',
);
?>

    
<div>
    
     <?php echo $this->zrayTable($tableParams); //zrayTableHtml ?>
        
</div>


<script type="text/javascript">
(function() {
	var storage = zray.getStorage('mlogs');
	// create main table
	var maintable = zray.createGeneralTreeTable(storage, jQuery('#<?php echo $tableParams['tableId']; ?>'));
	maintable.setColumns([
		{
			label: 'Message',
			propertyName: 'message',
			sortable:true,
			getHtml: function(val, rec) {
				var cushion = $zendDevBar('<div>');
				cushion.attr('title', val);
				return cushion.text(val);
			}
		},
		{
			label: 'Level',
			propertyName: 'level',
			sortable:true,
			width:70
		},
		{
			label: 'File',
			propertyName: 'file',
			sortable:true,
			width:150
		}
	]);
	zray.registerDataHandler('magento', 'mlogs', function(extensionData, requestData) {
		storage.setData(extensionData[0].logs);
		jQuery('[data-name="zrayExtension:magento/logs"] .zdb-toolbar-detail-header h1').append('<small style="margin-left: 10px;">Developer Mode: '+extensionData[0].devMode+'</small>');
		jQuery('[data-name="zrayExtension:magento/logs"] .zdb-toolbar-info').append(' ('+extensionData[0].logs.length+')');
	});

})();
</script>

