<?php 
$tableParams = array(
	'overview'=>array(
		'tableId' 			=> 'mage-overview-overview-tree',
	),
	'request'=>array(
		'tableId' 			=> 'mage-overview-request-tree',
	),
	'handles'=>array(
		'tableId' 			=> 'mage-overview-handles-tree',
	)
);
?>

<style>
[data-name="zrayExtension:magento/overview"] .tabs-table:not(.active){
	display:none;
}

</style>
<ul class="tabs">
	<li>
		<input type="radio" name="magento-tab" id="tab-magento-1" checked />
		<label for="tab-magento-1"><?php echo _t('Overview'); ?></label>
		<div id="tab-content-magento-1" class="tab-content">
			<?php echo $this->zrayTable($tableParams['overview']); //zrayTableHtml ?>
		</div>
	</li>
	<li>
		<input type="radio" name="magento-tab" id="tab-magento-2" />
		<label for="tab-magento-2"><?php echo _t('Requests'); ?></label>
		<div id="tab-content-magento-2" class="tab-content">
			<?php echo $this->zrayTable($tableParams['request']); //zrayTableHtml ?>
		</div>
	</li>
	<li>
		<input type="radio" name="magento-tab" id="tab-magento-3" />
		<label for="tab-magento-3"><?php echo _t('Handles'); ?></label>
		<div id="tab-content-magento-3" class="tab-content">
			<?php echo $this->zrayTable($tableParams['handles']); //zrayTableHtml ?>
		</div>
	</li>
</ul>

<script type="text/javascript">
(function() {
	var overviewStorage = zray.getStorage('overview');
	var overviewMaintable = zray.createTreeTable(overviewStorage, jQuery('#<?php echo $tableParams['overview']['tableId']; ?>'));
	
	var handlesStorage = zray.getStorage('handles');
	var handlesMaintable = zray.createGeneralTreeTable(handlesStorage, jQuery('#<?php echo $tableParams['handles']['tableId']; ?>'));
	handlesMaintable.setColumns([
		{
			label: 'Name',
			propertyName: 'name',
			sortable:true
		}
	]);
	
	var requestStorage = zray.getStorage('request');
	var requestMaintable = zray.createGeneralTreeTable(requestStorage, jQuery('#<?php echo $tableParams['request']['tableId']; ?>'));
	requestMaintable.setColumns([
		{
			label: 'Property',
			propertyName: 'property',
			sortable:true
		},
		{
			label: 'Init Value',
			propertyName: 'init',
			sortable:true
		},
		{
			label: 'Final Value',
			propertyName: 'final',
			sortable:true
		},
	]);
		
	zray.registerDataHandler('magento', 'overview', function(extensionData, requestData) {
		overviewStorage.setData(extensionData[0].overview);
		requestStorage.setData(extensionData[0].request);
		handlesStorage.setData(extensionData[0].handles);
		
		//jQuery('[data-name="zrayExtension:magento/overview"] .tabsButtons').prependTo(jQuery('[data-name="zrayExtension:magento/overview"] .zdb-col-3-wide .zdb-pull-right'));
	});

})();
var switchTab = function(tab){
	jQuery('[data-name="zrayExtension:magento/overview"] .active, [data-name="zrayExtension:magento/overview"] [checked]').removeClass('active').removeAttr('checked');
	jQuery('[data-name="zrayExtension:magento/overview"] [rel="'+tab.getAttribute('rel')+'"]').addClass('active');
	jQuery('[data-name="zrayExtension:magento/overview"] [rel="'+tab.getAttribute('rel')+'"] input').prop('checked',true).attr('checked',true);
}
</script>

