<?php 
$tableParams = array(
	'tableId' 			=> 'magento-overview-tree',
    'tableWidth'        => '4-wide',
);
?>
 
<?php echo $this->zrayTable($tableParams); //zrayTableHtml ?>


<script type="text/javascript">
(function() {
	var storage = zray.getStorage('magento-overview');
	// create main table
	var maintable = zray.createTreeTable(storage, jQuery('#<?php echo $tableParams['tableId']; ?>'));

	// create pager
	zray.createPager(storage, jQuery('#magento-overview-pager'));
	// create search
	zray.createSearch(storage, jQuery('#magento-overview-search'), maintable);
	
	zray.registerDataHandler('magento', 'moverview', function(extensionData, requestData) {
		storage.setData(extensionData);
	});
	
})();
</script>